version: '3'
services:
  web:
    build: .
    container_name: 'restaurant_review'
    command: gunicorn --bind 0.0.0.0:8000 restaurant_review.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: restaurant_review_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"