# Generated by Django 4.2.7 on 2023-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_visit_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
