# Generated by Django 4.2.7 on 2023-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_visit_restaurant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('restaurant', 'customer', 'date')},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='restaurant_name',
        ),
    ]
